### ISSUE TITLE
Doesn't work well with NerdTreeTabs

### ISSUE THREAD

**Issue by psjay** [mhinz/vim-sayonara#13] opened 2017-10-23 05:25 UTC
As this Gif shows, Soyonara will deleted all buffers when NerdTreeTabs activated.

![bugreport](https://user-images.githubusercontent.com/856285/31873369-609450be-b788-11e7-98e9-7fa750a02eb3.gif)

**Comment by mhinz** [comment] 2017-10-24 23:23
Thanks for bringing this up. I can reproduce it just fine.

Will commit a fix later today!

**Comment by mhinz** [comment] 2017-10-28 14:46
Okay, so this is intended behaviour. `:Sayonara` closes the window, `:Sayonara!` preserves it.

See https://github.com/mhinz/vim-sayonara#details. There are 2 windows, so `:Sayonara` will close the current window and delete the buffer afterwards.

When this happens, there will only be the NERDTreeTabs window left which triggers on WinEnter by quitting Vim. So, it's a NERDTreeTabs thing.

Instead of `:Sayonara` you can also just use `:close` and it will behave the same; closing Vim.

Compare these:

```
$ vim +'e file1 | e file2 | execute "NERDTreeTabsToggle" | wincmd p | Sayonara'
$ vim +'e file1 | e file2 | execute "NERDTreeTabsToggle" | wincmd p | close'
$ vim +'e file1 | e file2 | execute "NERDTreeTabsToggle" | wincmd p | execute "autocmd! NERDTreeTabs WinEnter" | close'
```

In the last case you will only be left with the NERDTreeTabs window, because `:Sayonara` closed the other one and we removed NERDTreeTabs autocmd that would quit Vim in such cases.

Putting it in a nutshell, just use `:Sayonara!` instead of `:Sayonara`. :-)

**Closed as completed by mhinz** 2017-10-28 14:46 UTC
